[package]
edition = "2021"
name = "unihan-gtk"
version = "0.1.0"

[dependencies]
gtk = { package = "gtk4", version = "0.4" }
once_cell = "1.10.0"
rusqlite = { version = "0.27.0", features = ["bundled"] }
zip = "0.5"
